blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://stackoverflow.com
    about: Maintainers are not available to provide support. Please ask and answer questions on StackOverflow or the like.
