---
name: Dispatch Test
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
      latestReleaseOverride: 'Latest release override'
        description: 'By default, only releases from master will be tagged as latest. If you want to override this behavior, set this to true'
        required: false
        type: boolean
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      publishTag: ${{ steps.publishTag.outputs.value }}
    steps:
      - id: publishTag
        run: echo "value=${{ github.event.inputs.branchName == 'master' && 'latest' || github.event.inputs.branchName }}" >> $GITHUB_OUTPUT
  printing:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo "publishTag is ${{ needs.prepare.outputs.publishTag }}"
    steps:
      - run: echo "resolved tag is ${{ github.event.inputs.latestReleaseOverride || github.ref_name == 'main' && 'latest' || github.ref_name }}"
