---
name: Dispatch Test
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
      latestPackageOverride:
        description: 'By default, only releases from master will be tagged as latest. If you want to override this behavior for non-master branches, set this to true'
        required: false
        type: boolean
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      publishTag: ${{ steps.publishTag.outputs.value }}  
      publishTag2: ${{ steps.publishTag2.outputs.value }} 
    steps:
      - id: publishTag
        run: echo "value=${{ github.event.inputs.branchName == 'master' && 'latest' || (fromJSON(github.event.inputs.latestPackageOverride) && 'latest' || github.event.inputs.branchName) }}" >> $GITHUB_OUTPUT
  printing:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo "publishTag is ${{ needs.prepare.outputs.publishTag }}"
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - run: echo "publishTag is ${{ needs.prepare.outputs.publishTag }}"
      - run: npm run ${{ needs.prepare.outputs.publishTag }}
