---
name: Dispatch Test
on:
  workflow_dispatch:
    inputs:
      PR_TITLE:
        description: 'PR title'
        required: true
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.inputs.PR_TITLE }}
    outputs:
      commitMessage: "Deploying commit ${{ steps.commitMessage.outputs.value }}"
    steps:
      - id: commitMessage
        run: echo "value=${{ env.PR_TITLE }}" >> $GITHUB_OUTPUT
  printing:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo "COMMIT_MESSAGE is ${{ needs.prepare.outputs.commitMessage }} ok?"
