---
name: Dispatch Test
on:
  workflow_dispatch:
    inputs:
      TEST_STRING:
        description: 'Test string'
        required: true
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      commitMessage: ${{ steps.commitMessage.outputs.value }}
    steps:
      - id: commitMessage
        run: |
          COMMIT_MESSAGE="${{ github.event.inputs.TEST_STRING }}"
          COMMIT_MESSAGE='${COMMIT_MESSAGE//"/}'
          echo "value=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
  printing:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo "COMMIT_MESSAGE is ${{ needs.prepare.outputs.commitMessage }} ok?"
