---
name: Dispatch Test
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
jobs:
  new-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "something not in main"
