---
name: Dispatch Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      commitMessage: ${{ steps.commitMessage.outputs.value }}
    steps:
      - id: commitMessage
        run: |
          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          echo "value=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          COMMIT_MESSAGE="${COMMIT_MESSAGE//,/}"
          echo "value=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
