name: draft-test
on:
  push:
    branches:
      - main
      - 'release/*'
      - 'next/*'
  pull_request:
    branches:
      - main
      - 'release/*'
      - 'next/*'
env:
  NODE_VERSION: '18'
jobs:
  run-happo:
    # if: ${{ ! (github.event.issue.pull_request && github.event.pull_request.draft == true) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event.issue.pull_request is ${{ github.event.issue.pull_request }}"
      - run: echo "github.event.pull_request.draft is ${{ github.event.pull_request.draft }}"
